# Generated by Django 3.0.8 on 2020-07-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TarFoodApp', '0002_customer_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='adress',
            new_name='address',
        ),
    ]
