# Generated by Django 3.0.8 on 2020-07-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TarFoodApp', '0006_orderdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[('Coocking', 'COOCKING'), ('Ready', 'READY'), ('On The Way', 'ON THE WAY'), ('Ready', 'DELIVERED')]),
        ),
    ]
