# Generated by Django 3.0.8 on 2020-07-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TarFoodApp', '0009_auto_20200728_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('COOCKING', 'COOCKING'), ('READY', 'READY'), ('ONTHEWAY', 'ON THE WAY'), ('DELIVERED', 'DELIVERED')], max_length=30),
        ),
    ]
