# Generated by Django 3.0.8 on 2020-07-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TarFoodApp', '0011_auto_20200728_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'COOCKING'), (2, 'READY'), (3, 'ON THE WAY'), (4, 'DELIVERED')]),
        ),
    ]
