# Generated by Django 3.0.8 on 2020-07-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TarFoodApp', '0012_auto_20200728_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='meal',
            new_name='name',
        ),
    ]
